### ISSUE TITLE
Why it can't find `azureml:diabetes_data:1` in job.yml?

### ISSUE THREAD

**Issue by piwawa** [rafaelvanbelle/mslearn-mlops#6]
If i use this setting, it will throw an error about message like "file not found" or "wrong path":

```
inputs:
  training_data: 
    type: uri_folder 
    path: azureml:diabetes_data:1
```

Only if i change code to this, it can work:

```
inputs:
  training_data: 
    type: uri_folder 
    path: ../experimentation/data
```

Is there any step in Azure ML workspace i missed before run `job.yml`?
